Update patch set 1
Patch Set 1:

Picking only this one donf fix the zip problem. Also a lot of error appear cherry picking the others commits, including it breaks the build.

fatal error: too many errors emitted, stopping now [-ferror-limit=]

Patch-set: 1
Reviewer: Daniel Monteiro <12240@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0